name: reference_parser
description: >-
  A pub package that allows you to parse strings for bible references.
  Can parse varying formats of references and multiple references at a time.
version: 1.1.2
homepage: https://github.com/joshpetit/reference_parser
issue_tracker:  https://github.com/joshpetit/reference_parser/issues
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  html: ^0.14.0+4
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4
