name: reference_parser
description: Parse strings to find the reference to bible verses
version: 0.0.1
homepage: https://github.com/joshpetit/reference_parser
issue_tracker:  https://github.com/joshpetit/reference_parser/issues
environment:
  sdk: '>=2.0.0 <3.0.0'
#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4
